# @format

name: Build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_artifacts: ${{ steps.build.outputs.build_artifacts }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - id: build
        run: |
          npx tsup
          echo "build_artifacts=dist" >> $GITHUB_OUTPUT
